START = {
    "_": "Message",
    "id": 1,
    "from_user": {
        "_": "User",
        "id": 5534952877,
        "is_self": False,
        "is_contact": False,
        "is_mutual_contact": False,
        "is_deleted": False,
        "is_bot": True,
        "is_verified": False,
        "is_restricted": False,
        "is_scam": False,
        "is_fake": False,
        "is_support": False,
        "is_premium": False,
        "first_name": "⛩ Аватарки | Бот",
        "username": "anime_4bot",
        "dc_id": 2,
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADAgADt8YxG21tiUoAEAIAA62t6EkBAAMEBDVJZTzOtwAEHgQ",
            "small_photo_unique_id": "AgADt8YxG21tiUo",
            "big_file_id": "AQADAgADt8YxG21tiUoAEAMAA62t6EkBAAMEBDVJZTzOtwAEHgQ",
            "big_photo_unique_id": "AgADt8YxG21tiUo",
        },
    },
    "date": "2023-01-01 00:00:00",
    "chat": {
        "_": "Chat",
        "id": 5534952877,
        "type": "ChatType.BOT",
        "is_verified": False,
        "is_restricted": False,
        "is_scam": False,
        "is_fake": False,
        "is_support": False,
        "username": "anime_4bot",
        "first_name": "⛩ Аватарки | Бот",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADAgADt8YxG21tiUoAEAIAA62t6EkBAAMEBDVJZTzOtwAEHgQ",
            "small_photo_unique_id": "AgADt8YxG21tiUo",
            "big_file_id": "AQADAgADt8YxG21tiUoAEAMAA62t6EkBAAMEBDVJZTzOtwAEHgQ",
            "big_photo_unique_id": "AgADt8YxG21tiUo",
        },
        "dc_id": 2,
    },
    "mentioned": False,
    "scheduled": False,
    "from_scheduled": False,
    "has_protected_content": False,
    "text": "⛩ Привет, Макс Соболь!\n\nЯ буду отправлять тебе аватарки и классные пикчи, которые ты сможешь использовать в своих диалогах 👌🏻\n\nДобавляй меня в свой чат или начинай пользоваться прямо здесь 😉",
    "entities": [
        {
            "_": "MessageEntity",
            "type": "MessageEntityType.TEXT_MENTION",
            "offset": 10,
            "length": 11,
            "user": {
                "_": "User",
                "id": 1980530667,
                "is_self": True,
                "is_contact": False,
                "is_mutual_contact": False,
                "is_deleted": False,
                "is_bot": False,
                "is_verified": False,
                "is_restricted": False,
                "is_scam": False,
                "is_fake": False,
                "is_support": False,
                "is_premium": False,
                "first_name": "Макс Соболь",
                "status": "UserStatus.OFFLINE",
                "last_online_date": "2023-01-01 00:00:00",
                "username": "max_sobol",
                "dc_id": 2,
                "phone_number": "*********",
                "photo": {
                    "_": "ChatPhoto",
                    "small_file_id": "AQADAgADzLkxGx4SYUsAEAIAA-t_DHYABBy5Tm184D0rAAQeBA",
                    "small_photo_unique_id": "AgADzLkxGx4SYUs",
                    "big_file_id": "AQADAgADzLkxGx4SYUsAEAMAA-t_DHYABBy5Tm184D0rAAQeBA",
                    "big_photo_unique_id": "AgADzLkxGx4SYUs",
                },
            },
        }
    ],
    "outgoing": False,
    "reply_markup": {
        "_": "InlineKeyboardMarkup",
        "inline_keyboard": [
            [
                {
                    "_": "InlineKeyboardButton",
                    "text": "⛩ Аниме авы",
                    "callback_data": "⛩ Аниме авы",
                },
                {
                    "_": "InlineKeyboardButton",
                    "text": "🎎 Парные аватарки",
                    "callback_data": "🎎 Парные аватарки",
                },
            ],
            [
                {
                    "_": "InlineKeyboardButton",
                    "text": "💖 Милые пикчи",
                    "callback_data": "💖 Милые пикчи",
                },
                {
                    "_": "InlineKeyboardButton",
                    "text": "😡 Агрессивные",
                    "callback_data": "😡 Агрессивные",
                },
            ],
            [
                {
                    "_": "InlineKeyboardButton",
                    "text": "💬 Добавить в чат",
                    "url": "https://t.me/anime_4bot?startgroup=0",
                }
            ],
        ],
    },
}
GET_AVATARS = {
    "_": "Message",
    "id": 1,
    "from_user": {
        "_": "User",
        "id": 5534952877,
        "is_self": False,
        "is_contact": False,
        "is_mutual_contact": False,
        "is_deleted": False,
        "is_bot": True,
        "is_verified": False,
        "is_restricted": False,
        "is_scam": False,
        "is_fake": False,
        "is_support": False,
        "is_premium": False,
        "first_name": "⛩ Аватарки | Бот",
        "username": "anime_4bot",
        "dc_id": 2,
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADAgADt8YxG21tiUoAEAIAA62t6EkBAAMEBDVJZTzOtwAEHgQ",
            "small_photo_unique_id": "AgADt8YxG21tiUo",
            "big_file_id": "AQADAgADt8YxG21tiUoAEAMAA62t6EkBAAMEBDVJZTzOtwAEHgQ",
            "big_photo_unique_id": "AgADt8YxG21tiUo",
        },
    },
    "date": "2023-01-01 00:00:00",
    "chat": {
        "_": "Chat",
        "id": 5534952877,
        "type": "ChatType.BOT",
        "is_verified": False,
        "is_restricted": False,
        "is_scam": False,
        "is_fake": False,
        "is_support": False,
        "username": "anime_4bot",
        "first_name": "⛩ Аватарки | Бот",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADAgADt8YxG21tiUoAEAIAA62t6EkBAAMEBDVJZTzOtwAEHgQ",
            "small_photo_unique_id": "AgADt8YxG21tiUo",
            "big_file_id": "AQADAgADt8YxG21tiUoAEAMAA62t6EkBAAMEBDVJZTzOtwAEHgQ",
            "big_photo_unique_id": "AgADt8YxG21tiUo",
        },
        "dc_id": 2,
    },
    "mentioned": False,
    "scheduled": False,
    "from_scheduled": False,
    "media": "MessageMediaType.PHOTO",
    "has_protected_content": False,
    "has_media_spoiler": False,
    "caption_entities": [
        {
            "_": "MessageEntity",
            "type": "MessageEntityType.TEXT_LINK",
            "offset": 3,
            "length": 20,
            "url": "https://t.me/avhelp3_bot",
        },
        {
            "_": "MessageEntity",
            "type": "MessageEntityType.BOLD",
            "offset": 3,
            "length": 20,
        },
    ],
    "caption": "💸 Купить рекламу здесь",
    "outgoing": False,
}
