[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "levch", email = "levchenko.d.a1998@gmail.com"},
]
dependencies = [
    "core @ file:///${PROJECT_ROOT}/core",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm.scripts]
_.env_file = "../.env"
start = "python src"