[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = []
dependencies = [
    "uvicorn>=0.20.0",
    "fastapi>=0.92.0",
    "mongoengine>=0.26.0",
]
requires-python = ">=3.10"
license = { text = "MIT" }

[tool.pdm.scripts]
_.env_file = "../.env"
start = "python src"
